name: dartvolt
description: Experimental API Wrapper for the REVOLT.chat API including basic HTTP and Websocket functionality.
homepage: https://github.com/janderedev/dartvolt
version: 0.0.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  web_socket_channel: ^2.1.0
  eventify: ^1.0.0

dev_dependencies:
  pedantic: ^1.9.0
